extends:
  - stylelint-config-recommended
  - stylelint-prettier/recommended
rules:
  unit-disallowed-list:
    - "px"
  declaration-property-value-allowed-list:
    "/color/":
    - "/^var\\(--/"
    - "transparent"
