# Copyright 2021 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.
version: '3'
services:
  e2e:
    image: node:14.17.0
    depends_on:
      - chrome
      - frontend
    environment:
      # CI is used for cleaner log output from jest and npm install
      - CI=true
      - GO_DISCOVERY_E2E_BASE_URL=http://frontend:8080
      - GO_DISCOVERY_E2E_CHROME_URL=ws://chrome:3000
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - WAITFORIT_TIMEOUT=300
    command: bash -c "
        ./third_party/wait-for-it/wait-for-it.sh frontend:8080 --
          npm install && npx jest e2e/basic.test.ts
        "
    volumes:
      - ../../:/pkgsite
    working_dir: /pkgsite
  chrome:
    image: browserless/chrome:1.46-chrome-stable
    ports:
      - 3000:3000
    environment:
      - CONNECTION_TIMEOUT=120000
  frontend:
    image: golang:1.15.5
    depends_on:
      - migrate
    command: bash -c "
        ./third_party/wait-for-it/wait-for-it.sh db:5432 --
          go run ./cmd/frontend -host=0.0.0.0:8080
        "
    environment:
      - GO_DISCOVERY_DATABASE_USER=postgres
      - GO_DISCOVERY_DATABASE_PASSWORD=postgres
      - GO_DISCOVERY_DATABASE_HOST=db
      - GO_DISCOVERY_DATABASE_NAME=discovery_e2e_test
      - WAITFORIT_TIMEOUT=300
      - PORT=8080
    ports:
      - 8080:8080
    volumes:
      - ../../:/pkgsite
    working_dir: /pkgsite
  migrate:
    depends_on:
      - db
    image: migrate/migrate:v4.14.1
    entrypoint: ""
    command: sh -c "
        apk add --no-cache bash &&
        ./third_party/wait-for-it/wait-for-it.sh db:5432 --
          migrate -path /pkgsite/migrations
            -database postgres://postgres:postgres@db:5432/discovery_e2e_test?sslmode=disable up"
    environment:
      - WAITFORIT_TIMEOUT=300
    volumes:
      - ../../:/pkgsite
    working_dir: /pkgsite
  db:
    image: postgres:11.12
    environment:
      - LANG=C
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=discovery_e2e_test
    ports:
        - 5428:5432
